# Generated by Django 6.0.3 on 2026-04-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phylo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='analysis_type',
            field=models.CharField(choices=[('UPGMA', 'Distance-based UPGMA'), ('NJ', 'Distance-based Neighbor Joining'), ('PARSIMONY', 'Character-based Parsimony')], max_length=20),
        ),
    ]
